"""Immediate spoken ack while Ripley works. Combinatorial, not a catchphrase.

Register: WarGames/WOPR, Ex Machina, Hackers, Swordfish, Sneakers,
Trainspotting, Withnail and I, Fight Club, Midnight in Paris / Hemingway,
Event Horizon, Jurassic Park, Back to the Future, Ghostbusters, Pi (1998),
Flight of the Navigator, and a wider film/lit pile. The line that always
unique: current time, then "Press return." Fragments most of the time;
full nods rarely.
Kyutai TTS only — no Cerebras round.
"""
from __future__ import annotations

import random
import re
import threading
from datetime import datetime

_OPEN = (
    "Yeah",
    "Mm",
    "Right",
    "Okay",
    "Got it",
    "Sure",
    "Alright",
    "On it",
    "Heard",
    "Copy",
    "Yep",
    "Okay yeah",
    "Mm-hm",
    "Fair",
    "Good",
    "Noted",
    "With you",
    "I'm here",
    "Stay with me",
    "Hang on",
    "Hold on",
    "Wait one",
    "Just a second",
    "Bear with me",
    "Let me look",
    "Let me pull that",
    "Let me see",
    "I'll take that",
    "Taking that",
    "Working it",
    "Verify me",
    "Play a game",
    "Shall we",
    "Hello Joshua",
    "I want in",
    "Going downtown",
    "Through the glass",
    "No more secrets",
    "Too many secrets",
    "Choose life",
    "Choose this",
    "We're out",
    "Lust for life",
    "We've gone on holiday by mistake",
    "I demand a minute",
    "I'm remaining in character",
    "First rule",
    "Second rule",
    "I am Jack's patience",
    "Hit me with it",
    "One true sentence",
    "Write it true",
    "Paris is a moveable feast",
    "Grace under pressure",
    "Pretty to think so",
    "Lost generation",
    "At the café",
    "The dude abides",
    "Make it so",
    "Fascinating",
    "There is no spoon",
    "Follow the white rabbit",
    "We need to go deeper",
    "I'm sorry Dave",
    "Houston",
    "Science the problem",
    "Fear is the mind-killer",
    "See you space cowboy",
    "I aim to misbehave",
    "These go to eleven",
    "Inconceivable",
    "You talkin' to me",
    "Round up the usual suspects",
    "Here's looking at you",
    "Forget it Jake",
    "Follow the money",
    "The game is on",
    "I am not a number",
    "This message will wait",
    "Always be looking",
    "I'm mad as hell",
    "Carpe the second",
    "Get in the van",
    "Don't advise a haircut",
    "Free to those who can afford it",
    "One minute at a time",
    "Not a unique snowflake",
    "Project later",
    "Bleed on the typewriter",
    "Never confuse movement with action",
    "The first draft can wait",
    "Isn't it pretty to think so",
    "Great Scott",
    "This is heavy",
    "Hello McFly",
    "Where we're going",
    "Hold on to your butts",
    "Clever girl",
    "Spared no expense",
    "Must go faster",
    "Life finds a way",
    "Back off man",
    "Who you gonna call",
    "Don't cross the streams",
    "He slimed me",
    "Important safety tip",
    "We came we saw",
    "Where we won't need eyes",
    "The ship is looking",
    "Libera te",
    "Save yourself from the lag",
    "Press return",
    "Stare into the sun",
    "Don't blink",
    "Two hundred sixteen",
    "Eat some pie",
    "Slow down Max",
    "I am Max",
    "I need a navigator",
    "You have been scanned",
    "We come in peace",
    "Compliance",
)

_MIDDLE = (
    "looking",
    "pulling that up",
    "digging",
    "checking",
    "one more look",
    "a second pass",
    "the interesting bit",
    "the real driver",
    "how this sits",
    "how this reads",
    "a cleaner angle",
    "the next useful cut",
    "what to put on glass",
    "whether this still matches",
    "the part that isn't boilerplate",
    "shall we play a game",
    "a strange game",
    "how about chess instead",
    "asking Joshua",
    "waking WOPR",
    "not thermonuclear war",
    "the only winning move",
    "is this a game or is it real",
    "through the glass",
    "BlueBook is quiet",
    "Ava's still behind the glass",
    "it's not the test I wanted",
    "power's still on",
    "hack the planet",
    "mess with the best",
    "no right and wrong, only fun and boring",
    "on the Gibson",
    "Crash Override style",
    "never send a boy",
    "we're elite or we're not",
    "my voice is my passport",
    "too many secrets",
    "no more secrets",
    "checking the box",
    "the good guys for a minute",
    "sixty seconds",
    "building a payload",
    "not a stealth bomber",
    "hydra can wait",
    "choosing life for a second",
    "relishing this one",
    "it's a chemical world",
    "not the worst toilet",
    "we're getting out",
    "holiday by mistake",
    "I demand to have some time",
    "a pig didn't sit on this",
    "Monty can wait",
    "this'll happen anyway",
    "I'm a trained actor about it",
    "get in the back of the van",
    "you do not talk about it yet",
    "I am Jack's complete lack of surprise",
    "I am Jack's smirking revenge",
    "the things you own",
    "lost everything useful",
    "hit me as hard as the data allows",
    "this is your life ending one minute at a time",
    "not a beautiful unique snowflake",
    "first rule of this turn",
    "second rule of this turn",
    "his name is Robert Paulson later",
    "one true sentence",
    "all you have to do is write one true sentence",
    "a moveable feast",
    "courage is grace under pressure",
    "the world breaks everyone",
    "you are all a lost generation",
    "never confuse movement with action",
    "the first draft of anything",
    "sit down and bleed a little",
    "pretty to think so",
    "at the Dingo",
    "Gertrude would cut this",
    "Gil's still in the car",
    "midnight in this problem",
    "there is no spoon",
    "the net is vast",
    "tears in rain later",
    "more human than human",
    "I'm sorry Dave I'm looking",
    "failure is not an option this second",
    "follow the money",
    "deep throat can wait",
    "the stuff that dreams are made of",
    "ready for my close-up",
    "the horror is a spreadsheet",
    "these go to eleven",
    "have you tried turning it to eleven",
    "inconceivable until it isn't",
    "as you wish, after this",
    "the dude abides in the query",
    "that rug really tied the room together",
    "we need to go deeper",
    "don't start Global Thermonuclear War",
    "see you space cowboy",
    "I aim to misbehave shortly",
    "live long and look",
    "make it so in a minute",
    "the spice must flow later",
    "fear is the mind-killer",
    "I am not a number",
    "I am a free man looking",
    "the game is on",
    "shaken not stirred",
    "usual suspects",
    "forget it Jake it's this filing",
    "you can't handle the truth yet",
    "I'm as mad as hell and I'm looking",
    "you talkin' to me or the figure",
    "here's looking at you kid",
    "we'll always have this cut",
    "of all the gin joints",
    "round up the usual suspects",
    "the beginning of a beautiful friendship",
    "I drink to make this more interesting",
    "true at first light",
    "a feast is moveable",
    "bleed on it then talk",
    "life finds a way",
    "whether they could, not whether they should",
    "hold on to your butts",
    "clever girl",
    "spared no expense",
    "must go faster",
    "objects in mirror",
    "it's a UNIX system, I know this",
    "you didn't say the magic word",
    "they're moving in herds",
    "welcome to the park",
    "1.21 gigawatts",
    "where we're going we don't need roads",
    "this is heavy",
    "flux capacitor charging",
    "eighty-eight miles per hour",
    "if you put your mind to it",
    "make like a tree",
    "save the clock tower",
    "enchantment under the sea",
    "great Scott",
    "hello McFly",
    "don't cross the streams",
    "it would be bad",
    "dogs and cats living together",
    "who you gonna call",
    "I ain't afraid of no ghost",
    "we came, we saw, we kicked its ass",
    "back off man, I'm a scientist",
    "there is no Dana, only Zuul",
    "are you the Keymaster",
    "are you the Gatekeeper",
    "tell him about the Twinkie",
    "the universe as an infinite Twinkie",
    "if someone asks if you're a god, you say yes",
    "we have the tools, we have the talent",
    "he slimed me",
    "important safety tip",
    "Stay Puft can wait",
    "nice shooting Tex",
    "I love this plan. I'm excited to be a part of it",
    "where we're going we won't need eyes to see",
    "hell is just a word",
    "the ship is alive",
    "it shows you things",
    "libera te tutemet",
    "save yourself from hell, then look",
    "the dark inside the query",
    "the event horizon of this filing",
    "Lewis and Clark can wait",
    "you're not seeing this yet",
    "staring into the sun",
    "forcing myself not to blink",
    "the brightness began to dissolve",
    "mother said not to look",
    "when I was six",
    "press return",
    "two hundred sixteen digits",
    "the pattern is in everything",
    "mathematics is the language of nature",
    "the market is a living organism",
    "rest and eat some pie",
    "slow down Max",
    "Euclid is quiet",
    "a number at the center",
    "I am Max",
    "Trimaxion is listening",
    "you have been scanned",
    "I need a navigator",
    "we come in peace",
    "star maps later",
    "eight years from now",
    "inside the ship time is different",
    "I'll take you home after this",
    "Puckmaren can wait",
    "R.A.L.F. is not helping",
    "compliance",
    "compliance, Navigator",
)

_TAIL = (
    "hold on",
    "stay with me",
    "give me a beat",
    "give me a second",
    "don't go anywhere",
    "one moment",
    "almost",
    "on it",
    "coming",
    "hang on",
    "wait one",
    "I've got this",
    "leave it with me",
    "I'll bring it back",
    "won't be long",
    "stay put",
    "keep talking if you want",
    "interrupt me if I'm wrong",
    "this won't take long",
    "then I'll talk",
    "then we can look together",
    "shall we play",
    "verify me",
    "hack the planet",
    "no more secrets",
    "see you downtown",
    "through the glass",
    "payload's cooking",
    "don't start Global Thermonuclear War",
    "choose life",
    "we're out of here in a minute",
    "relish it",
    "holiday by mistake",
    "I demand a second",
    "remaining in character",
    "first rule",
    "don't talk about it yet",
    "I am Jack's delay",
    "one minute at a time",
    "one true sentence",
    "pretty to think so",
    "grace under pressure",
    "lost generation for a beat",
    "the dude abides",
    "these go to eleven",
    "inconceivable",
    "no spoon yet",
    "deeper in a second",
    "I'm sorry Dave",
    "Houston wait",
    "make it so",
    "see you space cowboy",
    "misbehave shortly",
    "follow the money",
    "usual suspects",
    "here's looking at you",
    "a beautiful friendship",
    "typewriter later",
    "café after",
    "midnight can wait",
    "life finds a way",
    "hold on to your butts",
    "clever girl",
    "must go faster",
    "spared no expense",
    "great Scott",
    "this is heavy",
    "we don't need roads",
    "1.21 gigawatts",
    "don't cross the streams",
    "who you gonna call",
    "I ain't afraid of no ghost",
    "back off man",
    "important safety tip",
    "he slimed me",
    "where we won't need eyes",
    "the ship is alive",
    "libera te",
    "press return",
    "don't blink",
    "the brightness dissolves",
    "eat some pie",
    "slow down Max",
    "two sixteen",
    "I am Max",
    "navigator later",
    "you've been scanned",
    "we come in peace",
    "star maps after",
    "compliance",
    "compliance, Navigator",

)

_TEMPLATES = (
    "{open}. {middle}.",
    "{open} — {middle}.",
    "{open}. {tail}.",
    "{open} — {tail}.",
    "{middle}. {tail}.",
    "{open}. {middle} — {tail}.",
    "{open}, {middle}.",
    "{open}. {middle}, {tail}.",
    "{open} — {middle}. {tail}.",
    "{middle}. {open}, {tail}.",
    "{open}. {tail} {middle}.",
    "{open} — {middle}. {open}.",
)

_NOD = (
    "Shall we play a game?",
    "How about a nice game of chess?",
    "A strange game.",
    "Would you like to play a game?",
    "Hello, Joshua.",
    "Is this a game or is it real?",
    "The only winning move is not to play. Not this round.",
    "Let's go downtown.",
    "My voice is my passport. Verify me.",
    "Too many secrets.",
    "No more secrets.",
    "Hack the planet.",
    "Mess with the best, die like the rest.",
    "There is no right and wrong. Only fun and boring.",
    "Never send a boy to do a woman's job.",
    "I want in.",
    "We're going in.",
    "Through the glass.",
    "It's a test.",
    "Sixty seconds.",
    "Not an Apache. Not a stealth bomber. Just working.",
    "Choose life.",
    "I chose not to choose life. I chose this cut.",
    "We're out of here.",
    "Lust for life. One second.",
    "We've gone on holiday by mistake.",
    "I demand to have some booze. Metaphorically.",
    "I'm remaining in character.",
    "Get in the back of the van.",
    "This'll happen to you.",
    "Free to those who can afford it.",
    "First rule. You do not talk about it yet.",
    "Second rule. Same as the first.",
    "I am Jack's complete lack of surprise.",
    "I am Jack's smirking revenge.",
    "This is your life, and it's ending one minute at a time.",
    "You are not a beautiful unique snowflake. Hold on.",
    "I want you to hit me as hard as you can. With the question.",
    "The things you own end up owning you. Not this.",
    "His name is Robert Paulson. Later.",
    "Write one true sentence.",
    "All you have to do is write one true sentence.",
    "Paris is a moveable feast.",
    "Courage is grace under pressure.",
    "The world breaks everyone.",
    "You are all a lost generation.",
    "Never confuse movement with action.",
    "The first draft of anything is a mess. This isn't the draft.",
    "There is nothing to writing. Sit down at a typewriter and bleed.",
    "Isn't it pretty to think so?",
    "I drink to make other people more interesting. Looking anyway.",
    "A moveable feast. Stay put.",
    "There is no spoon.",
    "Follow the white rabbit.",
    "We need to go deeper.",
    "I'm sorry Dave. I'm looking.",
    "Houston, working the problem.",
    "Fear is the mind-killer.",
    "See you space cowboy.",
    "I aim to misbehave.",
    "These go to eleven.",
    "Inconceivable.",
    "The dude abides.",
    "That rug really tied the room together.",
    "You talkin' to me?",
    "Here's looking at you, kid.",
    "Round up the usual suspects.",
    "Forget it Jake. It's this turn.",
    "Follow the money.",
    "You can't handle the truth yet.",
    "I'm mad as hell and I'm going to look.",
    "Of all the gin joints.",
    "Louis, I think this is the beginning of a beautiful friendship.",
    "We'll always have this cut.",
    "I am not a number. I am a free man.",
    "The game is on.",
    "Make it so.",
    "Live long and look.",
    "The spice must flow later.",
    "More human than human.",
    "The net is vast and infinite.",
    "Tears in rain. After this.",
    "Never give up. Never surrender.",
    "I know kung fu. Not useful here.",
    "There is no right and wrong. Only this beat.",
    "My voice is my passport.",
    "Play it, Joshua.",
    "Would you like to play Global Thermonuclear War? No.",
    "How about a nice game of chess instead.",
    "Gentlemen, you can't fight in here. This is the looking room.",
    "I'm as mad as hell.",
    "We're gonna need a bigger boat. Or a better plot.",
    "I love the smell of a query in the morning.",
    "Say hello to my little figure.",
    "I'll be back. With the answer.",
    "Come with me if you want to look.",
    "Get to the chopper. Metaphorically.",
    "Yippee-ki-yay. Working.",
    "Nobody puts this cut in a corner.",
    "Have you tried turning it to eleven?",
    "It's only a flesh wound. Keep talking.",
    "We are the knights who say hold on.",
    "This is an ex-parrot until I'm done.",
    "Don't panic.",
    "So long, and thanks for the question.",
    "The answer is not forty-two yet.",
    "Winter is coming. This query first.",
    "A Lannister always pays his attention.",
    "I drink and I know things. Looking.",
    "Valar dohaeris. One second.",
    "That's no moon. That's a filing.",
    "Use the force, later.",
    "These aren't the droids. These are the numbers.",
    "Do or do not. I'm doing.",
    "I have a bad feeling about the boilerplate.",
    "Help me Obi-Wan. Help me the 8-K.",
    "Elementary.",
    "The game is afoot.",
    "Once more unto the breach.",
    "We few, we happy few, we band of queries.",
    "To be or not to be. To look.",
    "Though this be madness, yet there is method.",
    "I have of late, but wherefore I know not.",
    "Now is the winter of our data.",
    "A horse, a horse, my kingdom for a second.",
    "If music be the food of love, hold on.",
    "We are such stuff as dreams are made on.",
    "Lord, what fools these filings be.",
    "The lady doth protest too much. The 10-Q.",
    "Something wicked this way comes. Or a heatmap.",
    "Out, damned spot. Out, damned lag.",
    "Is this a dagger I see before me? No. A figure.",
    "Friends, Romans, spectators.",
    "I came, I saw, I queried.",
    "Alea iacta est. Looking.",
    "Carthago can wait.",
    "Et tu, 8-K.",
    "Life finds a way.",
    "Hold on to your butts.",
    "Clever girl.",
    "Spared no expense.",
    "Must go faster.",
    "It's a UNIX system. I know this.",
    "Ah ah ah. You didn't say the magic word.",
    "Your scientists were so preoccupied with whether they could.",
    "They didn't stop to think if they should. I am.",
    "Welcome to Jurassic Park.",
    "They're moving in herds.",
    "Great Scott.",
    "This is heavy.",
    "Roads? Where we're going, we don't need roads.",
    "1.21 gigawatts.",
    "If you put your mind to it, you can accomplish anything. Starting now.",
    "Hello, McFly.",
    "Make like a tree and look.",
    "Flux capacitor. Working.",
    "Eighty-eight miles per hour.",
    "Save the clock tower. After this.",
    "Who you gonna call?",
    "I ain't afraid of no ghost.",
    "We came, we saw, we kicked its ass.",
    "Back off, man. I'm a scientist.",
    "Don't cross the streams.",
    "It would be bad.",
    "Dogs and cats, living together. Mass hysteria.",
    "There is no Dana. Only Zuul. Later.",
    "He slimed me.",
    "Important safety tip. Thanks Egon.",
    "Tell him about the Twinkie.",
    "Ray, if someone asks you if you're a god, you say yes.",
    "We have the tools. We have the talent.",
    "I love this plan. I'm excited to be a part of it. Let's do it.",
    "Where we're going, we won't need eyes to see.",
    "Hell is just a word. The query is the thing.",
    "The ship is alive.",
    "It shows you things.",
    "Libera te tutemet ex inferis. Then look.",
    "Save yourself. I'm looking.",
    "You're not seeing this. Yet.",
    "When I was a little kid my mother told me not to stare into the sun.",
    "So once when I was six, I did.",
    "At first the brightness was overwhelming, but I had seen that before.",
    "I kept looking, forcing myself not to blink.",
    "Then the brightness began to dissolve.",
    "Press return.",
    "Rest and eat some pie.",
    "Slow down, Max.",
    "216.",
    "Mathematics is the language of nature.",
    "There is a pattern in everything.",
    "The stock market is a living organism. Looking anyway.",
    "I am Max.",
    "I need a navigator.",
    "You have been scanned.",
    "We come in peace.",
    "Inside the ship, time is different. Press return.",
    "I'll take you home. After this cut.",
    "Trimaxion drone ship. Working.",
    "Eight years late. Hold on.",
    "Compliance.",
    "Compliance. Navigator.",

)

_HOOK_RE = re.compile(
    r"\b(SLB|HAL|BKR|NOV|NWL|CRM|DOW|MU|8-K|Form\s*4|filings?|chord|"
    r"heatmap|timeline|density|Schlumberger|Halliburton|"
    r"Baker|oilfield|WOPR|Joshua|Gibson)\b",
    re.IGNORECASE,
)

_recent: list[str] = []
_mu = threading.Lock()
_RECENT = 256

assert len(_OPEN) * len(_MIDDLE) * len(_TAIL) * 3 > 1000


def _hook(utterance: str) -> str:
    found = _HOOK_RE.findall(utterance or "")
    if not found:
        return ""
    token = found[-1]
    token = re.sub(r"\s+", " ", token).strip()
    if len(token) > 16:
        return ""
    return token


def _clock(now: datetime | None = None) -> str:
    """Seconds included so two acks in the same minute still differ."""
    stamp = now or datetime.now().astimezone()
    return stamp.strftime("%H:%M:%S")


def press_return_line(
    *,
    now: datetime | None = None,
    rng: random.Random | None = None,
    open_: str | None = None,
) -> str:
    """Pi (1998): state the time, then press return. Always unique."""
    rng = rng or random.Random()
    clock = _clock(now)
    open_ = open_ or rng.choice(_OPEN)
    tail = rng.choice(_TAIL)
    return _clean(
        rng.choice(
            (
                f"{open_}. {clock}. Press return.",
                f"{open_}. It's {clock}. Press return.",
                f"{open_}. {clock}. Press return. {tail}.",
                f"{clock}. Compliance. Press return.",
                f"Compliance. {clock}. Press return.",
                f"{open_}. {clock}. Compliance. Press return.",
                f"When I was six I stared into the sun. {clock}. Press return.",
                f"The brightness began to dissolve. {clock}. Press return.",
                f"{open_}. {clock}. Two sixteen. Press return.",
            )
        )
    )


def _clean(text: str) -> str:
    text = " ".join((text or "").split())
    text = text.replace("..", ".")
    text = re.sub(r"\s+([.,—])", r"\1", text)
    text = re.sub(r"([.,]){2,}", r"\1", text)
    if text and text[-1] not in ".!?":
        text += "."
    if text and text[0].islower():
        text = text[0].upper() + text[1:]
    words = text.split()
    if len(words) > 18:
        text = " ".join(words[:18]).rstrip(".,") + "."
    return text


def ack_line(utterance: str = "", *, rng: random.Random | None = None) -> str:
    """One short spoken ack. Combinatorial; avoids the last few lines."""
    rng = rng or random.Random()
    hook = _hook(utterance)
    # Time + "Press return" is the uniqueness engine (Pi). Majority of acks.
    if rng.random() < 0.62:
        line = press_return_line(rng=rng)
        with _mu:
            _recent.append(line)
            del _recent[:-_RECENT]
        return line
    if not hook and rng.random() < 0.28:
        nod = rng.choice(_NOD)
        with _mu:
            if nod not in _recent:
                _recent.append(nod)
                del _recent[:-_RECENT]
                return nod
    middles = list(_MIDDLE)
    if hook:
        hooked = (
            f"on {hook}",
            f"looking at {hook}",
            f"pulling {hook}",
            f"the {hook} cut",
        )
        middles.extend(hooked)
        if rng.random() < 0.5:
            middles = list(hooked) * 4 + middles
    for _ in range(32):
        open_ = rng.choice(_OPEN)
        middle = rng.choice(middles)
        tail = rng.choice(_TAIL)
        if middle.lower() in open_.lower() or tail.lower() in open_.lower():
            continue
        if tail.lower() in middle.lower():
            continue
        line = rng.choice(_TEMPLATES).format(open=open_, middle=middle, tail=tail)
        line = _clean(line)
        if len(line) < 8:
            continue
        with _mu:
            if line in _recent:
                continue
            _recent.append(line)
            del _recent[:-_RECENT]
        return line
    return _clean(f"{rng.choice(_OPEN)}. {rng.choice(_TAIL)}.")


def space_size() -> int:
    return (
        len(_OPEN) * len(_MIDDLE) * len(_TAIL) * len(_TEMPLATES)
        + len(_NOD)
        + 86400  # HH:MM:SS × Press return
    )
